version: 2

before:
  hooks:
    - go mod tidy
builds:
  - binary: obsgod
    flags:
      - -trimpath
    ldflags: -s -w -X main.version={{ .Version }} -X main.commitSHA={{ .Commit }}
    goos:
      - linux
      - freebsd
      - openbsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - builds:
      - obsgod
    homepage: "https://github.com/szmyty/obsgod"
    maintainer: "szmyty"
    description: "obsgod is a command-line remote control for OBS"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
